version: '3.9'

services:
  frontend:
    build:
        context: ./frontend
    ports:
      - "3000:3000"
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      
  
  api:
    build:
        context: ./server
    ports:
      - "5000:5000"
    container_name: api
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file: .env

  db:
    image: postgres
    restart: always
    env_file: .env
      

